"""Differentiable torch implementation of the BBOB (COCO 2009 noiseless) suite.

Mirrors the interface of `encoder/cec2017_torch.py` (`CEC2017Torch`) so it can be
dropped into `AugmentedCEC2017`/the task pool: `BBOBTorch(fid, D, device)` is
callable on coords of shape (B, D) (float64), returns (B,) with gradients
flowing — required because TersQ BPTT differentiates through the objective.

Instance parameters (x_opt, f_opt, R, Q) are generated by a FAITHFUL port of
coco's `suite_bbob_legacy_code.c` RNG (verified bit-exact vs cocoex on f1, see
the __main__ validation harness). The RNG runs once at construction (numpy);
the __call__ math is pure torch and differentiable.

Reference: Hansen et al. 2009, "Real-Parameter Black-Box Optimization
Benchmarking 2009: Noiseless Functions Definitions".
"""
import math

import numpy as np
import torch

PI = math.pi


# ===========================================================================
# coco BBOB-2009 RNG (faithful port of suite_bbob_legacy_code.c) — numpy/host
# ===========================================================================
def bbob_unif(N, inseed):
    """Verbatim port of bbob2009_unif. Returns a list[float] of length N."""
    inseed = int(inseed)
    if inseed < 0:
        inseed = -inseed
    if inseed < 1:
        inseed = 1
    aktseed = inseed
    rgrand = [0] * 32
    for i in range(39, -1, -1):
        tmp = int(math.floor(aktseed / 127773.0))
        aktseed = 16807 * (aktseed - tmp * 127773) - 2836 * tmp
        if aktseed < 0:
            aktseed += 2147483647
        if i < 32:
            rgrand[i] = aktseed
    aktrand = rgrand[0]
    r = [0.0] * N
    for i in range(N):
        tmp = int(math.floor(aktseed / 127773.0))
        aktseed = 16807 * (aktseed - tmp * 127773) - 2836 * tmp
        if aktseed < 0:
            aktseed += 2147483647
        tmp = int(math.floor(aktrand / 67108865.0))
        aktrand = rgrand[tmp]
        rgrand[tmp] = aktseed
        r[i] = aktrand / 2.147483647e9
        if r[i] == 0.0:
            r[i] = 1e-99
    return r


def bbob_gauss(N, seed):
    """Verbatim port of bbob2009_gauss (Box-Muller). Returns list[float]."""
    u = bbob_unif(2 * N, seed)
    g = [0.0] * N
    for i in range(N):
        g[i] = math.sqrt(-2.0 * math.log(u[i])) * math.cos(2.0 * PI * u[N + i])
        if g[i] == 0.0:
            g[i] = 1e-99
    return g


def compute_xopt(seed, D):
    x = bbob_unif(D, seed)
    for i in range(D):
        x[i] = 8.0 * math.floor(1e4 * x[i]) / 1e4 - 4.0
        if x[i] == 0.0:
            x[i] = -1e-5
    return np.array(x, dtype=np.float64)


def _fmin(a, b):
    return a if a < b else b


def _fmax(a, b):
    return a if a > b else b


def _bround(x):
    return math.floor(x + 0.5)


def compute_fopt(function, instance):
    if function == 4:
        rseed = 3
    elif function == 18:
        rseed = 17
    else:
        rseed = function
    rrseed = rseed + 10000 * instance
    gval = bbob_gauss(1, rrseed)[0]
    gval2 = bbob_gauss(1, rrseed + 1)[0]
    return _fmin(1000.0, _fmax(-1000.0, _bround(100.0 * 100.0 * gval / gval2) / 100.0))


def compute_rotation(seed, D):
    """Faithful port of bbob2009_compute_rotation. Returns (D, D) np.float64.

    coco fills B column-major from the gauss vector (reshape: B[i][j] =
    vector[j*D + i]) then Gram-Schmidt orthonormalizes the COLUMNS.
    """
    g = bbob_gauss(D * D, seed)
    B = np.empty((D, D), dtype=np.float64)
    for i in range(D):
        for j in range(D):
            B[i][j] = g[j * D + i]
    for i in range(D):
        for j in range(i):
            prod = float(np.dot(B[:, i], B[:, j]))
            B[:, i] -= prod * B[:, j]
        B[:, i] /= math.sqrt(float(np.dot(B[:, i], B[:, i])))
    return B


# ===========================================================================
# Differentiable transform primitives (torch, hot path)
# ===========================================================================
def t_osc(x):
    """T_osz oscillation transform (element-wise, differentiable)."""
    xabs = torch.abs(x)
    xhat = torch.where(x != 0, torch.log(torch.clamp(xabs, min=1e-300)),
                       torch.zeros_like(x))
    c1 = torch.where(x > 0, torch.full_like(x, 10.0), torch.full_like(x, 5.5))
    c2 = torch.where(x > 0, torch.full_like(x, 7.9), torch.full_like(x, 3.1))
    sgn = torch.sign(x)
    return sgn * torch.exp(xhat + 0.049 * (torch.sin(c1 * xhat) + torch.sin(c2 * xhat)))


def t_asy(x, beta, D):
    """T_asy^beta asymmetry transform (only positive coords)."""
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    expo = 1.0 + beta * (i / max(D - 1, 1)) * torch.sqrt(torch.clamp(x, min=0.0))
    return torch.where(x > 0, x ** expo, x)


def lambda_diag(alpha, D, device, dtype):
    """Diagonal of Lambda^alpha: lambda_ii = alpha^(0.5 * i/(D-1))."""
    i = torch.arange(D, device=device, dtype=dtype)
    return alpha ** (0.5 * i / max(D - 1, 1))


def f_pen(x):
    """Boundary penalty sum(max(0,|x|-5)^2)."""
    return torch.sum(torch.clamp(torch.abs(x) - 5.0, min=0.0) ** 2, dim=1)


# ===========================================================================
# BBOBTorch — one (fid, D, instance) function, differentiable
# ===========================================================================
N_FUNCS = 24
DIMS_DEFAULT = (10,)


class BBOBTorch:
    def __init__(self, fid, D, device, instance=1, dtype=torch.float64):
        assert 1 <= fid <= N_FUNCS, f"BBOB fid must be 1..24, got {fid}"
        self.fid = int(fid)
        self.D = int(D)
        self.device = device
        self.dtype = dtype
        self.instance = int(instance)
        self.f_opt = float(compute_fopt(self.fid, self.instance))
        self.rseed = self.fid + 10000 * self.instance
        # x_opt (most functions); special-cased per function where needed
        xopt = compute_xopt(self.rseed, self.D)
        self.x_opt = torch.tensor(xopt, device=device, dtype=dtype)
        # Drop-in compatibility with the AugmentedCEC2017 / task-pool interface:
        # the trainer reads `.f_optimal` (known optimum value, for gap/hit) and
        # `.shift` (optimum LOCATION, for the disentangle/LUPI x_star — see
        # train_distributed._get_x_star, which uses .shift for plain fns).
        self.f_optimal = self.f_opt
        self.shift = self.x_opt
        # rotations (lazy per function): R = rot(rseed+1e6), Q = rot(rseed)
        self._R = None
        self._Q = None

    # -- rotation accessors (built on demand) --
    # coco convention (verified vs cocoex on f10): the PRIMARY rotation uses
    # seed rseed+1e6, the SECONDARY uses rseed. Two-rotation functions assign
    # rot1=R=rot(rseed+1e6), rot2=Q=rot(rseed) — validate per function vs cocoex.
    @property
    def R(self):
        if self._R is None:
            self._R = torch.tensor(compute_rotation(self.rseed + 1000000, self.D),
                                   device=self.device, dtype=self.dtype)
        return self._R

    @property
    def Q(self):
        if self._Q is None:
            self._Q = torch.tensor(compute_rotation(self.rseed, self.D),
                                   device=self.device, dtype=self.dtype)
        return self._Q

    def _rot(self, x, M):
        # x: (B, D); M: (D, D) acting as M @ (x)  -> (B, D)
        return x @ M.T

    # -- dispatch --
    def __call__(self, x):
        x = x.to(self.dtype)
        if x.dim() == 1:
            x = x.unsqueeze(0)
        fn = _REGISTRY.get(self.fid)
        if fn is None:
            raise NotImplementedError(f"BBOB f{self.fid} not yet implemented")
        return fn(self, x) + self.f_opt


# ---- function registry (filled below; workflow appends the rest) ----
_REGISTRY = {}


def _register(fid):
    def deco(fn):
        _REGISTRY[fid] = fn
        return fn
    return deco


# f1 — Sphere
@_register(1)
def _f1(self, x):
    z = x - self.x_opt
    return torch.sum(z * z, dim=1)


# f2 — Ellipsoidal separable: sum 10^(6 i/(D-1)) z_i^2 ; z = Tosz(x - xopt)
@_register(2)
def _f2(self, x):
    D = self.D
    z = t_osc(x - self.x_opt)
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    coeff = 10.0 ** (6.0 * i / max(D - 1, 1))
    return torch.sum(coeff * z * z, dim=1)


# f10 — Ellipsoidal rotated: z = Tosz(R (x - xopt)); sum 10^(6 i/(D-1)) z_i^2
@_register(10)
def _f10(self, x):
    D = self.D
    z = t_osc(self._rot(x - self.x_opt, self.R))
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    coeff = 10.0 ** (6.0 * i / max(D - 1, 1))
    return torch.sum(coeff * z * z, dim=1)




# ===========================================================================
# Functions f3..f24 (implemented + validated vs cocoex by the bbob-torch
# workflow, 2026-06-03; module-level helpers take `self` explicitly)
# ===========================================================================

# f3 — Rastrigin separable: z = Lambda^10 Tasy^0.2 Tosz(x - xopt)
@_register(3)
def _f3(self, x):
    D = self.D
    z = t_osc(x - self.x_opt)
    z = t_asy(z, 0.2, D)
    z = lambda_diag(10.0, D, x.device, x.dtype) * z
    s1 = torch.sum(torch.cos(2.0 * PI * z), dim=1)
    s2 = torch.sum(z * z, dim=1)
    return 10.0 * (D - s1) + s2


# f4 — Bueche-Rastrigin. coco rseed=3 for xopt/fopt; even-indexed xopt coords
# are abs'd; brs scaling = Lambda^10 with a conditional x10 on positive even
# coords; boundary penalty 100*f_pen.
@_register(4)
def _f4(self, x):
    D = self.D
    if getattr(self, "_f4_xopt", None) is None:
        # coco f4 uses rseed = 3 + 10000*instance for x_opt (NOT fid=4)
        xo = compute_xopt(3 + 10000 * self.instance, D)
        xo = torch.tensor(xo, device=x.device, dtype=x.dtype)
        idx = torch.arange(D, device=x.device)
        xo = torch.where(idx % 2 == 0, torch.abs(xo), xo)
        self._f4_xopt = xo
    z = t_osc(x - self._f4_xopt)
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    base = 10.0 ** (0.5 * i / max(D - 1, 1))
    even = (i.long() % 2 == 0)
    mult = torch.where((z > 0) & even, torch.full_like(z, 10.0),
                       torch.ones_like(z))
    z = base * mult * z
    s1 = torch.sum(torch.cos(2.0 * PI * z), dim=1)
    s2 = torch.sum(z * z, dim=1)
    return 10.0 * (D - s1) + s2 + 100.0 * f_pen(x)


# f5 — Linear Slope: xopt_i = 5*sign in {-5,+5}; s_i = sign(xopt_i)*10^(i/(D-1));
# z_i = x_i if x_i*xopt_i < 25 else xopt_i; f = sum(5|s_i| - s_i z_i).
@_register(5)
def _f5(self, x):
    D = self.D
    if getattr(self, "_f5_params", None) is None:
        sign = torch.sign(self.x_opt)
        xopt5 = 5.0 * sign
        i = torch.arange(D, device=x.device, dtype=x.dtype)
        s = sign * (10.0 ** (i / max(D - 1, 1)))
        self._f5_params = (xopt5, s)
    xopt5, s = self._f5_params
    z = torch.where(x * xopt5 < 25.0, x, xopt5)
    return torch.sum(5.0 * torch.abs(s) - s * z, dim=1)


# f6 — Attractive Sector: M = R Lambda^10 Q; z = M(x - xopt);
#      raw = sum_i s_i z_i^2, s_i = 100^2 if xopt_i*z_i>0 else 1;
#      obj = Tosz(raw)^0.9  (oscillate then power 0.9; raw>=0 -> t_osc exact)
@_register(6)
def _f6(self, x):
    D = self.D
    lam = lambda_diag(10.0, D, x.device, x.dtype)          # Lambda^10 diagonal
    xc = x - self.x_opt
    z = self._rot(lam * self._rot(xc, self.Q), self.R)      # R @ (Lambda * (Q @ (x-xopt)))
    s = torch.where(self.x_opt * z > 0.0,
                    torch.full_like(z, 100.0 * 100.0),
                    torch.ones_like(z))
    raw = torch.sum(s * z * z, dim=1)
    return t_osc(raw) ** 0.9


# f7 — Step Ellipsoidal (monolithic coco function):
#   x_tmp = Lambda^10 * (Q (x - xopt)); x1 = x_tmp[0]
#   round-step (coco floor(.+0.5)): |x_tmp|>0.5 -> floor(x_tmp+0.5) else floor(10 x_tmp+0.5)/10
#   xx = R x_round; result = 0.1*max(|x1|*1e-4, sum 100^(i/(D-1)) xx_i^2) + penalty (scale 1.0)
@_register(7)
def _f7(self, x):
    D = self.D
    cond = 100.0
    lam = lambda_diag(10.0, D, x.device, x.dtype)          # sqrt(100^(i/(D-1)))
    xt = lam * self._rot(x - self.x_opt, self.Q)           # Lambda * (Q @ (x-xopt))
    x1 = xt[:, 0]
    big = torch.floor(xt + 0.5)                            # coco_double_round = floor(.+0.5)
    small = torch.floor(10.0 * xt + 0.5) / 10.0
    xr = torch.where(torch.abs(xt) > 0.5, big, small)
    xx = self._rot(xr, self.R)                             # R @ x_round
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    coeff = cond ** (i / max(D - 1, 1))
    quad = torch.sum(coeff * xx * xx, dim=1)
    inner = 0.1 * torch.maximum(torch.abs(x1) * 1.0e-4, quad)
    return inner + f_pen(x)                                # penalty_scale = 1.0


# --- module-level helper for f8 (lazy 0.75-scaled xopt cache) ---
def _rosen_xopt8(self):
    if getattr(self, "_f8_xopt", None) is None:
        xo = compute_xopt(self.rseed, self.D) * 0.75
        self._f8_xopt = torch.tensor(xo, device=self.device, dtype=self.dtype)
    return self._f8_xopt


# f8 — Rosenbrock (separable): z = factor*(x - 0.75*xopt) + 1; factor=max(1,sqrt(D)/8)
#      raw = 100*sum (z_i^2 - z_{i+1})^2 + sum (z_i - 1)^2
@_register(8)
def _f8(self, x):
    D = self.D
    factor = max(1.0, math.sqrt(D) / 8.0)
    z = factor * (x - _rosen_xopt8(self)) + 1.0
    s1 = torch.sum((z[:, :-1] ** 2 - z[:, 1:]) ** 2, dim=1)
    s2 = torch.sum((z[:, :-1] - 1.0) ** 2, dim=1)
    return 100.0 * s1 + s2


# f9 — Rosenbrock rotated: z = factor*(Q @ x) + 0.5; factor=max(1,sqrt(D)/8)
#      NOTE: coco uses rotation(rseed) == self.Q here (NOT rseed+1e6/self.R); no xopt shift.
#      raw = 100*sum (z_i^2 - z_{i+1})^2 + sum (z_i - 1)^2
@_register(9)
def _f9(self, x):
    D = self.D
    factor = max(1.0, math.sqrt(D) / 8.0)
    z = factor * self._rot(x, self.Q) + 0.5
    s1 = torch.sum((z[:, :-1] ** 2 - z[:, 1:]) ** 2, dim=1)
    s2 = torch.sum((z[:, :-1] - 1.0) ** 2, dim=1)
    return 100.0 * s1 + s2


# f11 — Discus: z = Tosz(R(x - xopt)); 1e6 z_0^2 + sum_{i>=1} z_i^2
@_register(11)
def _f11(self, x):
    z = t_osc(self._rot(x - self.x_opt, self.R))
    return 1.0e6 * z[:, 0] ** 2 + torch.sum(z[:, 1:] ** 2, dim=1)


# f12 — Bent Cigar: SPECIAL x_opt uses seed rseed+1e6.
# z = R Tasy^0.5(R(x - xopt)); z_0^2 + 1e6 sum_{i>=1} z_i^2
@_register(12)
def _f12(self, x):
    if getattr(self, "_f12_xopt", None) is None:
        xo = compute_xopt(self.rseed + 1000000, self.D)
        self._f12_xopt = torch.tensor(xo, device=x.device, dtype=x.dtype)
    z = self._rot(x - self._f12_xopt, self.R)
    z = t_asy(z, 0.5, self.D)
    z = self._rot(z, self.R)
    return z[:, 0] ** 2 + 1.0e6 * torch.sum(z[:, 1:] ** 2, dim=1)


# f13 — Sharp Ridge: M = R1 @ Lambda^10 @ R2, z = M(x - xopt).
# R1=rot(rseed+1e6)=self.R, R2=rot(rseed)=self.Q.
# z_0^2 + 100 sqrt(sum_{i>=1} z_i^2)
@_register(13)
def _f13(self, x):
    D = self.D
    lam = lambda_diag(10.0, D, x.device, x.dtype)  # 10^(0.5 i/(D-1)) = sqrt(10)^(i/(D-1))
    y = self._rot(x - self.x_opt, self.Q)          # R2 (x - xopt)
    y = lam * y                                     # Lambda^10
    z = self._rot(y, self.R)                        # R1
    return z[:, 0] ** 2 + 100.0 * torch.sqrt(torch.sum(z[:, 1:] ** 2, dim=1))


# f14 — Different Powers: z = R(x - xopt); sqrt( sum |z_i|^(2 + 4 i/(D-1)) )
@_register(14)
def _f14(self, x):
    D = self.D
    z = self._rot(x - self.x_opt, self.R)
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    expo = 2.0 + 4.0 * i / max(D - 1, 1)
    return torch.sqrt(torch.sum(torch.abs(z) ** expo, dim=1))


# f15 — Rastrigin rotated: z = R Lambda^0.5(alpha=10) Q T_asy^0.2( T_osz( R (x - xopt) ) )
# COCO allocate registers (inner->outer effect): shift(xopt), affine(rot1),
# oscillate, asymmetric(0.2), affine(M=rot1.Lambda^0.5.rot2). The outermost
# (last-registered) transform runs FIRST on input, so the data flow on x is:
#   x - xopt  ->  R(.)  ->  T_osz  ->  T_asy^0.2  ->  M(.)   [M = R.Lambda^0.5.Q]
# NOTE: T_osz is applied BEFORE T_asy (decorator order), not asy-then-osz.
# R = rot(rseed+1e6) = coco rot1, Q = rot(rseed) = coco rot2.
@_register(15)
def _f15(self, x):
    D = self.D
    lam = lambda_diag(10.0, D, x.device, x.dtype)   # Lambda^0.5, alpha=10
    y = self._rot(x - self.x_opt, self.R)           # R (x - xopt)
    y = t_osc(y)                                     # T_osz
    y = t_asy(y, 0.2, D)                             # T_asy^0.2
    # M @ y with M = R @ diag(lam) @ Q  ==  R( lam * (Q y) )
    z = self._rot(y, self.Q)                         # Q y
    z = z * lam                                      # Lambda^0.5 Q y
    z = self._rot(z, self.R)                         # R Lambda^0.5 Q y = M y
    sum1 = torch.sum(torch.cos(2.0 * PI * z), dim=1)
    sum2 = torch.sum(z * z, dim=1)
    return 10.0 * (D - sum1) + sum2


# f16 — Weierstrass: z = R Lambda^0.5(alpha=1/100) Q T_osz( R (x - xopt) )
# base = 10 * ( (1/D) sum_i sum_{k=0..11} a^k cos(2 pi b^k (z_i + 0.5)) - f0 )^3
#   with a=0.5, b=3, f0 = sum_k a^k cos(2 pi b^k * 0.5).
# objective penalty (transform_obj_penalize, outermost) = (10/D) * f_pen(raw x).
# COCO allocate registers (inner->outer effect): shift(xopt), affine(rot1),
# oscillate, affine(M=rot1.Lambda^0.5.rot2), penalize(10/D). Data flow on x:
#   x - xopt -> R(.) -> T_osz -> M(.)   ;  penalty added on the ORIGINAL x.
# No asymmetry. R = rot(rseed+1e6) = rot1, Q = rot(rseed) = rot2.
_F16_F0 = sum((0.5 ** k) * math.cos(2.0 * PI * (3.0 ** k) * 0.5) for k in range(12))

@_register(16)
def _f16(self, x):
    D = self.D
    lam = lambda_diag(0.01, D, x.device, x.dtype)   # Lambda^0.5, alpha=1/100 -> base 0.1
    y = self._rot(x - self.x_opt, self.R)           # R (x - xopt)
    y = t_osc(y)                                     # T_osz
    # M @ y with M = R @ diag(lam) @ Q
    z = self._rot(y, self.Q)                         # Q y
    z = z * lam                                      # Lambda^0.5 Q y
    z = self._rot(z, self.R)                         # R Lambda^0.5 Q y = M y
    k = torch.arange(12, device=x.device, dtype=x.dtype)
    ak = 0.5 ** k                                    # (12,)
    bk = 3.0 ** k                                    # (12,)
    terms = ak * torch.cos(2.0 * PI * bk * (z.unsqueeze(-1) + 0.5))  # (B, D, 12)
    s = torch.sum(terms, dim=(1, 2))                 # (B,)
    base = 10.0 * (s / D - _F16_F0) ** 3
    pen = (10.0 / D) * f_pen(x)
    return base + pen


def _schaffers(self, x, conditioning, penalty_scale, x_opt=None, R=None, Q=None):
    """Schaffers F7 core (shared by f17 and f18).

    coco transform stack (f_schaffers_bbob_problem_allocate), evaluated on x in
    this order (vars transforms apply in REVERSE of allocate order):
        z = x - xopt
        z = R @ z                     # R = rot1 = rotation(rseed+1e6)
        z = T_asy^0.5(z)
        z = Lambda * (Q @ z)          # Q = rot2 = rotation(rseed);
                                      #   Lambda_ii = conditioning^(0.5 i/(D-1))
    raw = (sum_i (z_i^2+z_{i+1}^2)^0.25 (1+sin(50 (z_i^2+z_{i+1}^2)^0.1)^2) /(D-1))^2
    out = raw + penalty_scale * f_pen(ORIGINAL x)   # penalty on untransformed x
    (f_opt added by __call__).
    """
    D = self.D
    if x_opt is None:
        x_opt, R, Q = self.x_opt, self.R, self.Q
    z = x - x_opt
    z = self._rot(z, R)
    z = t_asy(z, 0.5, D)
    z = self._rot(z, Q)
    lam = lambda_diag(conditioning, D, x.device, x.dtype)  # (D,)
    z = lam * z
    s = z[:, :-1] ** 2 + z[:, 1:] ** 2  # (B, D-1)
    term = s ** 0.25 * (1.0 + torch.sin(50.0 * s ** 0.1) ** 2)
    result = (torch.sum(term, dim=1) / (D - 1.0)) ** 2
    result = result + penalty_scale * f_pen(x)
    return result


# f17 — Schaffers F7 (conditioning=10, penalty_scale=10). Standard rseed=17.
@_register(17)
def _f17(self, x):
    return _schaffers(self, x, conditioning=10.0, penalty_scale=10.0)


# f18 — Schaffers F7 ill-conditioned (conditioning=1000, penalty_scale=10).
# coco passes rseed_17 = 17 + 10000*instance (NOT 18) to the allocator, so xopt
# AND both rotations use the f17 seed. f_opt is already special-cased in
# compute_fopt (function==18 -> rseed=17), so __call__ adds the correct f_opt;
# only xopt/R/Q need the rseed override here.
@_register(18)
def _f18(self, x):
    if getattr(self, "_f18_xopt", None) is None:
        rseed17 = 17 + 10000 * self.instance
        self._f18_xopt = torch.tensor(
            compute_xopt(rseed17, self.D), device=x.device, dtype=x.dtype)
        self._f18_R = torch.tensor(
            compute_rotation(rseed17 + 1000000, self.D), device=x.device, dtype=x.dtype)
        self._f18_Q = torch.tensor(
            compute_rotation(rseed17, self.D), device=x.device, dtype=x.dtype)
    return _schaffers(self, x, conditioning=1000.0, penalty_scale=10.0,
                      x_opt=self._f18_xopt, R=self._f18_R, Q=self._f18_Q)


# f19 — Composite Griewank-Rosenbrock F8F2 (facftrue=10).
# coco transform stack (f_griewank_rosenbrock_bbob_problem_allocate):
#   scales = max(1, sqrt(D)/8); M = scales * rot1 (rot1 = rotation(rseed) = self.Q)
#   allocate order: shift(-0.5) then affine(M) -> affine is OUTER (applied FIRST):
#       z = M @ x = scales * (rot1 @ x)
#       z = z + 0.5            # transform_vars_shift with shift_i=-0.5 -> z - (-0.5)
#   raw: for i: c1=z_i^2 - z_{i+1}; c2=1 - z_i; t=100 c1^2 + c2^2; add t/4000 - cos t
#   out = facftrue + facftrue * sum/(D-1)   (facftrue=10). f_opt added by __call__.
# NOTE: x_opt/f_opt for f19 use the standard rseed=19; xopt isn't needed by the math
# (the affine has zero bias), so self.x_opt is unused here.
@_register(19)
def _f19(self, x):
    D = self.D
    scales = max(1.0, math.sqrt(D) / 8.0)
    z = scales * self._rot(x, self.Q)  # self.Q = rotation(rseed) = coco rot1
    z = z + 0.5
    c1 = z[:, :-1] ** 2 - z[:, 1:]
    c2 = 1.0 - z[:, :-1]
    tmp = 100.0 * c1 * c1 + c2 * c2
    inner = torch.sum(tmp / 4000.0 - torch.cos(tmp), dim=1)
    facftrue = 10.0
    return facftrue + facftrue * inner / (D - 1.0)


# f20 — Schwefel
@_register(20)
def _f20(self, x):
    D = self.D
    dev, dt = x.device, x.dtype
    if getattr(self, "_f20_params", None) is None:
        u = bbob_unif(D, self.rseed)
        xopt = np.array([(-1.0 if u[i] < 0.5 else 1.0) * 0.5 * 4.2096874637
                         for i in range(D)], dtype=np.float64)
        # x_hat sign vector uses the SAME unif(rseed) draw
        sgn = np.array([-1.0 if u[i] < 0.5 else 1.0 for i in range(D)],
                       dtype=np.float64)
        self._f20_params = (
            torch.tensor(np.abs(xopt), device=dev, dtype=dt),   # |xopt|
            torch.tensor(sgn, device=dev, dtype=dt),
        )
    absxopt, sgn = self._f20_params

    # COCO transform chain (outermost->innermost as applied to the input):
    #   x_hat -> scale(2) -> z_hat -> shift(2|xopt|) -> cond(10)
    #   -> shift(-2|xopt|) -> scale(100) -> raw Schwefel
    x2 = 2.0 * (sgn * x)                                  # x_hat then scale(2)
    z0 = x2[:, :1]
    z_rest = x2[:, 1:] + 0.25 * (x2[:, :-1] - 2.0 * absxopt[:-1].unsqueeze(0))
    z = torch.cat([z0, z_rest], dim=1) if D > 1 else z0  # z_hat
    z = z - (2.0 * absxopt).unsqueeze(0)                  # shift(tmp2=2|xopt|)
    z = lambda_diag(10.0, D, dev, dt).unsqueeze(0) * z    # conditioning(10)
    z = z + (2.0 * absxopt).unsqueeze(0)                  # shift(tmp1=-2|xopt|)
    z = 100.0 * z                                         # scale(100)

    penalty = torch.sum(torch.clamp(torch.abs(z) - 500.0, min=0.0) ** 2, dim=1)
    # sqrt(|z|) grad is +inf at z=0; clamp the radicand (forward unchanged).
    s = torch.sum(z * torch.sin(torch.sqrt(torch.clamp(torch.abs(z), min=1e-300))),
                  dim=1)
    return 0.01 * (penalty + 418.9828872724339 - s / D)


# ---- shared Gallagher helpers (module-level; used by f21 and f22) ----
def _gallagher_params(self, num_peaks):
    """Build (rotation, arr_scales(P,D), x_local(P,D), peak_values(P)) for the
    BBOB Gallagher problem. Faithful port of f_gallagher_bbob_problem_allocate."""
    D = self.D
    dev, dt = self.device, self.dtype
    maxcondition = 1000.0
    maxcondition1 = 1000.0
    fitvalues = (1.1, 9.1)
    if num_peaks == 101:
        maxcondition1 = math.sqrt(maxcondition1)
        b, c = 10.0, 5.0
    elif num_peaks == 21:
        b, c = 9.8, 4.9
    else:
        raise ValueError(f"unsupported number_of_peaks {num_peaks}")

    rotation = compute_rotation(self.rseed, D)  # seed = rseed (== self.Q)

    # peak conditions + values via a sort-permutation of (num_peaks-1) unifs
    rn = bbob_unif(num_peaks - 1, self.rseed)
    perm = sorted(range(num_peaks - 1), key=lambda i: rn[i])  # qsort by value
    arr_cond = np.empty(num_peaks, dtype=np.float64)
    peak_values = np.empty(num_peaks, dtype=np.float64)
    arr_cond[0] = maxcondition1
    peak_values[0] = 10.0
    for i in range(1, num_peaks):
        arr_cond[i] = maxcondition ** (perm[i - 1] / (num_peaks - 2))
        peak_values[i] = ((i - 1) / (num_peaks - 2)
                          * (fitvalues[1] - fitvalues[0]) + fitvalues[0])

    # per-peak diagonal scales Lambda^alpha_i, dim-permuted
    arr_scales = np.empty((num_peaks, D), dtype=np.float64)
    for i in range(num_peaks):
        rnj = bbob_unif(D, self.rseed + 1000 * i)
        permj = sorted(range(D), key=lambda j: rnj[j])
        for j in range(D):
            arr_scales[i, j] = arr_cond[i] ** (permj[j] / (D - 1) - 0.5)

    # peak positions (rotated), peak 0 scaled by 0.8
    rn2 = bbob_unif(D * num_peaks, self.rseed)
    x_local = np.zeros((num_peaks, D), dtype=np.float64)  # [peak][dim]
    for i in range(D):
        for j in range(num_peaks):
            s = 0.0
            for k in range(D):
                s += rotation[i, k] * (b * rn2[j * D + k] - c)
            x_local[j, i] = s * 0.8 if j == 0 else s

    return (
        torch.tensor(rotation, device=dev, dtype=dt),
        torch.tensor(arr_scales, device=dev, dtype=dt),     # (P, D)
        torch.tensor(x_local, device=dev, dtype=dt),        # (P, D)
        torch.tensor(peak_values, device=dev, dtype=dt),    # (P,)
    )


def _gallagher_raw(self, x, num_peaks, cache_attr):
    D = self.D
    params = getattr(self, cache_attr, None)
    if params is None:
        params = _gallagher_params(self, num_peaks)
        setattr(self, cache_attr, params)
    rotation, arr_scales, x_local, peak_values = params

    pen = torch.sum(torch.clamp(torch.abs(x) - 5.0, min=0.0) ** 2, dim=1)
    tmx = x @ rotation.T                                       # (B, D)
    diff = tmx.unsqueeze(1) - x_local.unsqueeze(0)            # (B, P, D)
    quad = torch.sum(arr_scales.unsqueeze(0) * diff * diff, dim=2)  # (B, P)
    vals = peak_values.unsqueeze(0) * torch.exp(-0.5 / D * quad)
    f = 10.0 - torch.max(vals, dim=1).values                 # (B,)

    a = 0.1
    pos, neg = f > 0, f < 0
    lt_p = torch.log(torch.clamp(f, min=1e-300)) / a
    ft_p = torch.pow(torch.exp(lt_p + 0.49 * (torch.sin(lt_p)
                     + torch.sin(0.79 * lt_p))), a)
    lt_n = torch.log(torch.clamp(-f, min=1e-300)) / a
    ft_n = -torch.pow(torch.exp(lt_n + 0.49 * (torch.sin(0.55 * lt_n)
                      + torch.sin(0.31 * lt_n))), a)
    f_true = torch.where(pos, ft_p, torch.where(neg, ft_n, f))
    return f_true * f_true + pen


# f21 — Gallagher 101 peaks
@_register(21)
def _f21(self, x):
    return _gallagher_raw(self, x, 101, "_gal101_params")


# f22 — Gallagher 21 peaks
# NOTE: relies on the module-level _gallagher_params / _gallagher_raw helpers
# defined alongside f21 above; do not redefine them.
@_register(22)
def _f22(self, x):
    return _gallagher_raw(self, x, 21, "_gal21_params")


# f23 — Katsuura
# z = M (x - xopt), M = R1 @ Lambda^100 @ R2 ; R1=rot(rseed+1e6)=R, R2=rot(rseed)=Q
# Lambda^100 diag = 100^(0.5 i/(D-1)) = lambda_diag(100,...). Boundary penalty
# f_pen is on the ORIGINAL x (coco transform_obj_penalize, factor 1.0).
@_register(23)
def _f23(self, x):
    D = self.D
    R1 = self.R          # rot(rseed + 1e6)
    R2 = self.Q          # rot(rseed)
    lam = lambda_diag(100.0, D, x.device, x.dtype)        # (D,)
    M = R1 @ (lam[:, None] * R2)                          # (D, D)
    z = (x - self.x_opt) @ M.T                            # (B, D)
    j = torch.arange(1, 33, device=x.device, dtype=x.dtype)   # 1..32
    two_j = 2.0 ** j                                      # (32,)
    zz = z.unsqueeze(-1) * two_j                          # (B, D, 32)
    tmp = torch.sum(torch.abs(zz - torch.round(zz)) / two_j, dim=-1)  # (B, D)
    i = torch.arange(D, device=x.device, dtype=x.dtype)
    per_dim = 1.0 + (i + 1.0) * tmp                       # (B, D)
    expo = 10.0 / (D ** 1.2)
    prod = torch.prod(per_dim ** expo, dim=1)             # (B,)
    raw = (10.0 / (D * D)) * (-1.0 + prod)
    return raw + f_pen(x)


# f24 — Lunacek bi-Rastrigin
# mu0=2.5, d=1, s=1-0.5/(sqrt(D+20)-4.1), mu1=-sqrt((mu0^2-d)/s)
# NON-standard xopt: sign = sign(bbob_gauss(D, rseed)); only its sign enters x_hat.
# x_hat = 2*sign*x; tmpvect = Lambda^100 @ R2 @ (x_hat-mu0); z = R1 @ tmpvect.
# R1=rot(rseed+1e6)=R, R2=rot(rseed)=Q. sum1/sum2 use x_hat; sum3=cos(2 pi z).
@_register(24)
def _f24(self, x):
    D = self.D
    mu0 = 2.5
    d = 1.0
    s = 1.0 - 0.5 / (math.sqrt(D + 20.0) - 4.1)
    mu1 = -math.sqrt((mu0 * mu0 - d) / s)
    if not hasattr(self, "_f24_sign"):
        g = bbob_gauss(D, self.rseed)
        sign = np.where(np.array(g) < 0.0, -1.0, 1.0)
        self._f24_sign = torch.tensor(sign, device=x.device, dtype=x.dtype)
    sign = self._f24_sign
    R1 = self.R          # rot(rseed + 1e6)
    R2 = self.Q          # rot(rseed)
    lam = lambda_diag(100.0, D, x.device, x.dtype)        # (D,) = 100^(0.5 i/(D-1))
    x_hat = 2.0 * sign * x                                # (B, D)
    diff0 = x_hat - mu0                                   # (B, D)
    tmpvect = (diff0 @ R2.T) * lam                        # (B, D)
    z = tmpvect @ R1.T                                    # (B, D)
    sum1 = torch.sum(diff0 * diff0, dim=1)
    diff1 = x_hat - mu1
    sum2 = torch.sum(diff1 * diff1, dim=1)
    sum3 = torch.sum(torch.cos(2.0 * math.pi * z), dim=1)
    bi = torch.minimum(sum1, d * D + s * sum2)
    return bi + 10.0 * (D - sum3) + 1e4 * f_pen(x)


# ===========================================================================
# Validation harness vs cocoex
# ===========================================================================
if __name__ == "__main__":
    import cocoex

    dev = "cuda" if torch.cuda.is_available() else "cpu"
    rng = np.random.default_rng(0)
    print(f"Validating implemented BBOB funcs vs cocoex (device={dev})\n")
    for fid in sorted(_REGISTRY):
        for D in (10,):
            for inst in (1, 2, 3):
                suite = cocoex.Suite(
                    "bbob", "",
                    f"dimensions: {D} instance_indices: {inst} function_indices: {fid}")
                p = suite[0]
                xs = rng.uniform(-5, 5, size=(64, D))
                ref = np.array([p(xi) for xi in xs])
                fn = BBOBTorch(fid, D, dev, instance=inst)
                got = fn(torch.tensor(xs, device=dev, dtype=torch.float64)).cpu().numpy()
                err = np.abs(got - ref)
                rel = err / (np.abs(ref) + 1e-12)
                ok = np.max(rel) < 1e-6 or np.max(err) < 1e-6
                print(f"  f{fid:02d} D{D} i{inst}: max|abs|={err.max():.3e} "
                      f"max|rel|={rel.max():.3e}  {'OK' if ok else 'FAIL'}")
        # gradient check
        fn = BBOBTorch(fid, 10, dev, instance=1)
        xg = torch.rand(4, 10, device=dev, dtype=torch.float64, requires_grad=True)
        fn(xg).sum().backward()
        print(f"  f{fid:02d} grad flows: {xg.grad is not None and torch.isfinite(xg.grad).all().item()}")
